#! /bin/sh
#
if [ $# != 0 ] ; then
  for f in ${*} ; do
    case=`basename $f .tst`
    if test -s $case.diff ; then
      echo -n "$case : "
      cat $case.diff
      echo -n "OK? "
      read x
      if test "$x" = "y" ; then
        ok $case
      fi
    fi
  done
else
  for f in *.tst ; do
    case=`basename $f .tst`
    if test -s $case.diff ; then
      echo -n "$case : "
      cat $case.diff
      echo -n "OK? "
      read x
      if test "$x" = "y" ; then
        ok $case
      fi
    fi
  done
fi
