#! /bin/sh
#
for f in *.alan ; do
  case=`basename $f .alan`
  echo -n "$case : "
  if [ -f $case.input ]
  then
    echo "has input file => promote to .."
  else
    echo "has no input file => promote to ../../compiler/testing"
  fi
done
