#! /bin/sh
#
for f in ${*} ; do
    case=`basename $f .alan`
    cp $case.output $case.expected
    rm $case.diff
    touch $case.diff
    cvs add $case.expected
    cvs commit $case.expected
done

