build:
    image: xenial
    env:
        - LD_LIBRARY_PATH=/usr/local/lib
    commands:
        - sudo apt-get -q update
        - sudo apt-get -q autoremove
        - sudo DEBIAN_FRONTEND=noninteractive apt-get -q install libc6-dev-i386
        - sudo DEBIAN_FRONTEND=noninteractive apt-get -q install zip
        - sudo DEBIAN_FRONTEND=noninteractive apt-get -q install wget
        - wget https://github.com/cgreen-devs/cgreen/releases/download/1.0.0/cgreen_1.0.0_amd64.deb
        - sudo dpkg -D1 -i cgreen_1.0.0_amd64.deb
        - echo $BUILD_ID > BUILD_NUMBER
        - make unit
        - make build
        - make JREGROUTPUT=-noansi test
        - make package
notify:
  slack:
    webhook_url: 'https://hooks.slack.com/services/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'
    username: 'drone'
    channel: '#general'
    template: >
              Alan build #{{ build.number }} finished with a {{ build.status }} status
    on_started: false
    on_success: true
    on_failure: true
