sudo: false
language: c

# Build matrix
compiler:
  - gcc

addons:
  apt:
    packages:
    -
    - lcov

before_install:
  - gem install coveralls-lcov

script:
  - java --version
  - make
  - make unit
  - make test

after_success:
  - lcov -d compiler -d interpreter -c -o coverage.info
  - lcov --remove coverage.info '/usr/*' -o coverage.info
  - coveralls-lcov build/coverage.info
