language: c
dist: bionic

# Build matrix
compiler:
  - gcc

addons:
  apt:
    packages:
    - lcov

before_install:
  - gem install coveralls-lcov
  - wget https://github.com/cgreen-devs/cgreen/releases/latest/download/cgreen_1.2.0_amd64.deb
  - sudo apt install ./cgreen_1.2.0_amd64.deb

script:
  - make unit
  - make COVERAGE=--coverage JREGROUTPUT=-noansi
  - make test JREGROUTPUT=-noansi

after_success:
  - lcov -d compiler/.alan -d interpreter/.arun -c -o coverage.info
  - lcov --remove coverage.info '/usr/*' -o coverage.info
  - coveralls-lcov coverage.info
