sudo: false
language: c

# Build matrix
compiler:
  - gcc

addons:
  apt:
    packages:
    - lcov

before_install:
  - gem install coveralls-lcov

script:
<<<<<<< HEAD
=======
  - java --version
  - make JREGROUTPUT=-noansi
>>>>>>> Add -noansi to .travis.yml output
  - make unit
  - make COVERAGE=--coverage JREGROUTPUT=-noansi
  - make test JREGROUTPUT=-noansi
  - cat regression/*.output

after_success:
  - lcov -d compiler/.alan -d interpreter/.arun -c -o coverage.info
  - lcov --remove coverage.info '/usr/*' -o coverage.info
  - coveralls-lcov coverage.info
