language: c
dist: bionic

# Build matrix
compiler:
  - gcc

addons:
  apt:
    packages:
    - lcov

install:
  - gem install coveralls-lcov
  - wget https://github.com/cgreen-devs/cgreen/releases/latest/download/cgreen_1.2.0_amd64.deb
  - sudo apt install ./cgreen_1.2.0_amd64.deb
  - npm i -g xunit-viewer

script:
  - make COVERAGE=--coverage ci
  - xunit-viewer --output=alan-tests.html

after_success:
  - lcov -d compiler/.alan -d interpreter/.arun -c -o coverage.info
  - lcov --remove coverage.info '/usr/*' -o coverage.info
  - lcov --list coverage.info
  - coveralls-lcov coverage.info
