language: c
dist: bionic
if: NOT tag =~ ^Build\d+$

# Build matrix
compiler:
  - gcc

addons:
  apt:
    packages:
    - lcov

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov
  - wget https://github.com/cgreen-devs/cgreen/releases/download/1.3.0/cgreen_1.3.0_amd64.deb
  - sudo apt-get install ./cgreen_1.3.0_amd64.deb
  - npm i -g xunit-viewer

script:
  - make COVERAGE=--coverage JREGROUTPUT="-xml" UNITOUTPUT="--xml TEST"
  - xunit-viewer -r . --output=alan-tests.html

after_success:
  - lcov -d compiler/.alan -d interpreter/.arun -c -o coverage.info
  - lcov --remove coverage.info '/usr/*' -o coverage.info
  - coveralls-lcov coverage.info
