/*----------------------------------------------------------------------*\

  alan.version.c

  The Alan version, composed from the two generated headers:

    alan_version.h  the release, from the top level VERSION file
    git_revision.h  the commit it was built from, and its date

  Neither is committed. This file used to be generated by venum and
  committed with a build timestamp in it, which is why it looked like
  something you were supposed to leave alone. It is ordinary source
  now, but there is still nothing here to edit at release time -- bump
  VERSION instead.

\*----------------------------------------------------------------------*/

#include "alan.version.h"

#include "alan_version.h"
#include "git_revision.h"

Product alan = {
  "Alan " ALAN_VERSION_STRING,
  "Alan " ALAN_VERSION_STRING " -- Adventure Language System (" GIT_DATE " " GIT_TIME ")",
  GIT_DATE,
  GIT_TIME,
  {ALAN_VERSION_STRING, ALAN_VERSION, ALAN_REVISION, ALAN_CORRECTION, ALAN_STATE}
};
