include mk/include_guard.mk

# Cross-compilation to Windows
include Makefile.win32

DISTDIR	:= ~/Utveckling/Alan/alanweb/downloads

# Since we only distribute windows 32-bit exe's
PLATFORM = windows-x86_64

# Location of Inno Setup Compiler
INNODIR = /cygdrive/c/Program\ Files\ \(x86\)/Inno\ Setup\ 6

# To get buildnumber remotely from Jenkins
XPATH = xpath -q -e

# Also build documentation
EXTRA_TARGET += documentation
