#######################################################################
include mk/include_guard.mk
#
# This Makefile is included from Makefile.common if running on ThoNi's
# machines, which are Windows machines. This primarily handles the release
# process.
#

CHANGES_HEADER = `head -1 CHANGES`

.PHONY: release
release:
	# Do some checking before building the release...
	@if ! printf -- '%s' "$(CHANGES_HEADER)" | egrep -q -- "$(VERSION)" ; then \
		echo "CHANGES is not updated for $(VERSION)" ; \
		exit 1 ; \
	else if ! git --no-pager diff --exit-code --quiet ; then \
		echo "Commit changes before making a release" ; \
		exit 1 ; \
	else if ! git --no-pager diff --exit-code --quiet --cached ; then \
		echo "Commit cached changes before making a release" ; \
		exit 1 ; \
	else if ! [[ -z `git rev-list @{upstream}.. -n 1` ]] ; then \
		echo "Push all local changes before making a release" ; \
		exit 1 ; \
	fi fi fi fi
	# Enable WinAlan & WinArun if not enabled already
ifeq ($(WINALAN_ENABLED),)
	@echo Enable WinAlan
	cp compiler/Makefile.local.template compiler/Makefile.local
	echo "WINALAN_ENABLED=true" >> compiler/Makefile.local
else
	@echo WinAlan already enabled! Good!
endif
ifeq ($(WINALAN_ENABLED),)
	@echo Enable WinArun
	cp interpreter/Makefile.local.template interpreter/Makefile.local
	echo "WINARUN_ENABLED=true" >> interpreter/Makefile.local
else
	@echo WinArun already enabled! Good!
endif
	$(MAKE) releasebuild
	$(MAKE) test
	# We won't make documentation since that is in the Alan Documentation project now
	#$(MAKE) documentation
	$(MAKE) zip setup
	$(MAKE) tags
	$(MAKE) release-upload


.PHONY: snapshot-upload
snapshot-upload: buildnumbers
	bin/alanupload $(CROSS_PACKAGE) snapshots/$(BUILDNAME)
	bin/alanupload $(WINALAN_PACKAGE) snapshots/$(BUILDNAME)
	bin/alanupload $(WINARUN_PACKAGE) snapshots/$(BUILDNAME)
	#ssh alanif.se ls -td /www/downloads/snapshots/Build* | tail -1 | xargs ssh alanif.se rm -r
	# Use lftp scripting instead? - lftp sftp:alanif.se

.PHONY: release-upload
release-upload:
	bin/alanupload $(CROSS_PACKAGE) sdks/windows
	bin/alanupload $(WINALAN_PACKAGE) sdks/windows
	bin/alanupload $(WINARUN_PACKAGE) interpreters/windows
	bin/alanupload interpreter/gargoyle-updater-alan$(VERSION).$(PLATFORM).setup.exe interpreters/windows
	bin/alanupload interpreter/gargoyle-updater-alan$(VERSION).$(PLATFORM).zip interpreters/windows


.PHONY: releasebuild
releasebuild:
	$(MAKE) -C compiler release
	$(MAKE) -C interpreter release
	$(MAKE) -C converter release

# Tag the release. The tag is what makes a release build identifiable:
# with it 'git describe' yields a bare v$(VERSION), while without it
# builds keep counting from the previous release tag. So it has to be
# pushed, or CI and the other platforms cannot produce a release
# marking at all. The per-OS branch stays local.
#
# Deliberately not forced. If the push is rejected because the tag is
# already on the remote then the release was published, and moving it
# is a considered 'git push --force origin v$(VERSION)', not something
# this target should do quietly.
.PHONY: tags
tags: last-release
	git tag -f v$(VERSION)
	git branch -f v$(VERSION)_$(OS)
	git push origin v$(VERSION)
	@echo "Tagged and pushed v$(VERSION)."
	@echo "Now bump ALAN_CORRECTION in VERSION and commit, to open the next cycle."

.PHONY: last-release
last-release:
	echo -n $(VERSION) > LASTRELEASE

#################################################################################

.PHONY: package
package: zip setup
# From Makefile.win32

# Gargoyle Arun
.PHONY: gararun
gararun:
	$(MAKE) -C interpreter gararun
