include mk/include_guard.mk

VERSION := $(shell cat NEXTRELEASE)
DISTDIR	:= ~/Utveckling/Alan/alanweb/downloads

# Since we only distribute windows 32-bit exe's
# TODO: Do/will we?
PLATFORM = win32.i686

# Location of Inno Setup Compiler
INNODIR = /c/Program\ Files\ \(x86\)/Inno\ Setup\ 5

# To get buildnumber remotely from Jenkins
XPATH = xpath -q -e
