# Top level Makefile for Alan on MacosX
#

VERSION	= `cat LASTRELEASE`

dist: alan arun
	tar zcvf alan$(VERSION).macosx.ppc.tgz alan arun alan.readme.macosx alan.readme CHANGES

alan: compiler/alan
	cp compiler/alan .

compiler/alan:
	cd compiler; make -f Makefile.macosx

arun: interpreter/arun
	cp interpreter/arun .

interpreter/arun:
	cd interpreter; make -f Makefile.unix
