include mk/include_guard.mk

VERSION	:= `venum alan -print '$$v.$$r{s$$s|_}$$c' | tr -d '\n\r'`
DISTDIR	:= ~/Utveckling/Alan/alanweb/downloads

# Since we only distribute windows 32-bit exe's
PLATFORM = win32.i686

# Location of Inno Setup Compiler
INNODIR = /cygdrive/c/Program\ Files\ \(x86\)/Inno\ Setup\ 5

# To get buildnumber remotely from Jenkins
XPATH = xpath -q -e

# Also build documentation
EXTRA_TARGET += documentation
