#!/bin/sh
#
# Generate a header with the Alan version, from the components in the
# top level VERSION file.
#
# Usage: alan-version.sh <output-header> <version> <revision> <correction> <state> <string>
#
# The components and the composed release string are passed in by
# mk/alan_version.mk, so the composition rule lives in one place.
#
# The header is rewritten only when something changed, so that an
# unchanged version does not force a rebuild of everything that
# includes it. The file is generated, and must never be committed.

output=$1
if [ $# -ne 6 ] ; then
    echo "Usage: $0 <output-header> <version> <revision> <correction> <state> <string>" >&2
    exit 1
fi

temporary=$output.$$.tmp
cat > "$temporary" <<EOF
/* Generated by mk/alan-version.sh from VERSION -- do not edit, do not commit */
#ifndef _alan_version_generated_h_
#define _alan_version_generated_h_

#define ALAN_VERSION $2
#define ALAN_REVISION $3
#define ALAN_CORRECTION $4
#define ALAN_STATE "$5"
#define ALAN_VERSION_STRING "$6"

#endif
EOF

if [ -f "$output" ] && cmp -s "$temporary" "$output" ; then
    rm -f "$temporary"
else
    mv "$temporary" "$output"
fi
