#!/bin/sh
#
# Generate a header defining GIT_REVISION, a string identifying the
# source revision a build was made from.
#
# Usage: git-revision.sh <output-header>
#
# The header is rewritten only when the revision actually changed, so
# that an unchanged revision does not force a rebuild of everything
# that includes it. This is why the file is written via a temporary
# and compared, rather than just generated every time.
#
# The file is generated, and must never be committed.

output=$1
if [ -z "$output" ] ; then
    echo "Usage: $0 <output-header>" >&2
    exit 1
fi

# --tags     also consider lightweight tags, not just annotated ones
# --dirty    mark builds made from a modified working tree
# --always   fall back to a bare commit hash if there is no tag
revision=`git describe --abbrev=8 --dirty --always --tags 2>/dev/null` || revision=""

if [ -z "$revision" ] ; then
    # No git, or not a git working tree, e.g. building from a source
    # package. Then there is nothing to identify the source with.
    revision="unknown"
fi

temporary=$output.$$.tmp
cat > "$temporary" <<EOF
/* Generated by mk/git-revision.sh -- do not edit, do not commit */
#ifndef _git_revision_h_
#define _git_revision_h_

#define GIT_REVISION "$revision"

#endif
EOF

if [ -f "$output" ] && cmp -s "$temporary" "$output" ; then
    rm -f "$temporary"
else
    mv "$temporary" "$output"
fi
