#!/bin/sh
#
# Generate a header defining GIT_REVISION, a string identifying the
# source revision a build was made from, and GIT_DATE/GIT_TIME, when
# that source was committed.
#
# Usage: git-revision.sh <output-header>
#
# The header is rewritten only when the revision actually changed, so
# that an unchanged revision does not force a rebuild of everything
# that includes it. This is why the file is written via a temporary
# and compared, rather than just generated every time.
#
# The file is generated, and must never be committed.

output=$1
if [ -z "$output" ] ; then
    echo "Usage: $0 <output-header>" >&2
    exit 1
fi

# Release tags are dotted, as in v3.0beta8. Matching only those keeps the
# Jenkins Build<n> tags, the older underscored v3_0* spelling, the whole v2
# range and structural markers such as v3_base out of the running, so the
# revision is always anchored to an actual release.
#
# --tags     also consider lightweight tags, not just annotated ones. Release
#            tags here are lightweight, so without this the recent ones are
#            invisible and describe silently reaches back to an ancient
#            annotated tag instead.
# --dirty    mark builds made from a modified working tree
# --always   fall back to a bare commit hash when no tag matches, which is
#            what happens before the first dotted tag, v3.0beta6
revision=`git describe --abbrev=8 --dirty --always --tags --match 'v[0-9]*.[0-9]*' 2>/dev/null` || revision=""

if [ -z "$revision" ] ; then
    # No git, or not a git working tree, e.g. building from a source
    # package. Then there is nothing to identify the source with.
    revision="unknown"
fi

# The commit date, not the build date. Two people building the same
# commit then get the same version output, which the build clock that
# venum used to stamp in here could never give.
committed=`git log -1 --format=%cd --date=format:'%Y-%m-%d %H:%M:%S' 2>/dev/null` || committed=""
if [ -z "$committed" ] ; then
    committed="unknown unknown"
fi
date=`echo "$committed" | cut -d' ' -f1`
time=`echo "$committed" | cut -d' ' -f2`

temporary=$output.$$.tmp
cat > "$temporary" <<EOF
/* Generated by mk/git-revision.sh -- do not edit, do not commit */
#ifndef _git_revision_h_
#define _git_revision_h_

#define GIT_REVISION "$revision"
#define GIT_DATE "$date"
#define GIT_TIME "$time"

#endif
EOF

if [ -f "$output" ] && cmp -s "$temporary" "$output" ; then
    rm -f "$temporary"
else
    mv "$temporary" "$output"
fi
