all: pre3.0alpha5.a3c pre3.0beta2.a3c pre3.0beta3.a3c

pre3.0alpha5.a3c : versions.alan
	./alan3.0alpha4 versions.alan
	mv versions.a3c pre3.0alpha5.a3c

pre3.0beta2.a3c : versions.alan
	./alan3.0alpha4 versions.alan
	mv versions.a3c pre3.0beta2.a3c

pre3.0beta3.a3c : versions.alan
	./alan3.0beta2 versions.alan
	mv versions.a3c pre3.0beta3.a3c

