#! /bin/sh
#
for f in ${*} ; do
    case=`basename $f .tst`
    examdiff $case.output $case.tst.expected
    echo -n "OK? "
    read x
    if test "$x" = "y" ; then
        ok $case
    fi
done
