#! /bin/sh
#
# Script for regression testing of Alan and Arun
#
failed=0
if [ $# != 0 ] ; then
  for f in ${*} ; do
    case=`basename $f .alan`
    if [ "$case" != "$f" ]
    then
	echo -n "$case : "
	echo "########## $case ##########" >$case.output
	cat $case.alan >>$case.output
	echo "########## alan $case.alan ##########" >>$case.output
	../bin/alan $case >>$case.output 2>&1
	../bin/arun -n $case >>$case.output 2>&1 < $case.input
	if diff -q -b $case.output $case.expected
	then
	    echo -n "[K"
	    rm $case.output
	else
	    failed=`expr $failed + 1`
	    echo "failed!"
	fi
    fi
  done
else
  for f in *.alan ; do
    case=`basename $f .alan`
    echo -n "$case : "
    echo "########## $case ##########" >$case.output
    cat $case.alan >> $case.output
    echo "########## alan $case.alan ##########" >>$case.output
    ../bin/alan $case >>$case.output 2>&1
    ../bin/arun -n $case >>$case.output 2>&1 < $case.input
    if diff -q -b $case.output $case.expected
    then
	echo -n "[K"
	rm $case.output
    else
      failed=`expr $failed + 1`
      echo "failed!"
    fi
  done
fi
if test $failed -eq 0
then
  echo All OK!
else
  echo "*** $failed failed! ***"
fi

