#! /bin/sh
#
# Script for regression testing of Alan and Arun
#

run ()
{
    echo -n "$case : "
    if [ ! -f $case.suspended ]
    then
	echo "########## alan $case ##########" >$case.output
	../bin/alan $case >>$case.output 2>&1
	echo "########## arun $case ##########" >>$case.output
	../bin/arun -r -n $case >>$case.output 2>&1 <$case.input 
	cases=`expr $cases + 1`
    fi
}

verify()
{
    if [ -f $case.suspended ]
    then
	suspended=`expr $suspended + 1`
	echo "Suspended..."
    else if [ -f $case.expected ]
    then
	if diff -q -b --strip-trailing-cr $case.output $case.expected 1> /dev/null
	then
	    ok=`expr $ok + 1`
	    echo -n "[K"
	    rm $case.output
	else
	    failed=`expr $failed + 1`
	    echo "*** FAILED!!! ***"
	fi
    else
	new=`expr $new + 1`
	echo "NEW!"
    fi
    fi
}

cases=0
ok=0
failed=0
suspended=0
new=0
if [ $# != 0 ] ; then
  for f in ${*} ; do
    case=`basename $f .alan`
    if [ "$case" != "$f" ]
    then
	run
	verify
    elif [ -f $case.alan ]
    then
        run
	verify
    fi
  done
else
  for d in *; do
    if [ -d $d ]
    then
	if [ -f $d/regr ]
	then
	    echo "Recursing: $d"
	    cd $d; regr; cd ..
	    echo "Leaving: $d"
	fi
    fi
  done

  for f in *.alan ; do
    case=`basename $f .alan`
    run
    verify
  done
fi
if test $new -ne 0
then
  echo -n "$new new, "
fi
if test $suspended -ne 0
then
  echo -n "$suspended suspended, "
fi
if test $failed -eq 0
then
  if test $new -eq 0
  then
    echo All $cases OK!
  else
    echo $ok OK!
  fi
else
  echo "*** $failed FAILED! ***"
fi
