#! /bin/sh
#
# Script for regression testing of Alan and Arun
#

run ()
{
    echo -n "$case : "
    ../bin/alan $case
    ../bin/arun -n $case <$case.input 
    cases=`expr $cases + 1`
}

cases=0
if [ $# != 0 ] ; then
  for f in ${*} ; do
    case=`basename $f .alan`
    if [ "$case" != "$f" ]
    then
	run
    elif [ -f $case.alan ]
    then
        run
    fi
  done
else
  for f in *.alan ; do
    case=`basename $f .alan`
    run
    verify
  done
fi
