version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc'
      - run:
          name: Installing buildessentials
          command: 'apt-get install -y build-essential'
      - run:
          name: Run CI build
          command: 'make ci'
      - store_test_results:
          path: ~/test-results
