version: 2
jobs:
  build:
    machine:
        image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run:
          name: Installing GCC, buildessentials and wget
          command: apt-get update && apt-get install -y gcc build-essential wget
      - run:
          name: Install cgreen
          command: wget https://github.com/cgreen-devs/cgreen/releases/download/1.3.0/cgreen_1.3.0_amd64.deb && apt install -y ./cgreen_1.3.0_amd64.deb
      - run:
          name: Install JRE
          command: apt install -y default-jre
      - run:
          name: Unittests
          command: make UNITOUTPUT=--xml\ TEST unit
      - run:
          name: Build
          command: make JREGROUTPUT=-xml
      - run:
          name: Test
          command: make JREGROUTPUT=-xml test
      - run:
          name: List test result files
          command: find . -name 'TEST*.xml'
      - run:
          name: Copy test results
          command: find . -iname 'TEST*.xml' | xargs xargs -I{} cp -p {} test_results
      - store_test_results:
          path: test_results
