version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run:
          name: Installing GCC, buildessentials and wget
          command: apt-get update && apt-get install -y gcc build-essential wget
      - run:
          name: Install cgreen
          command: wget https://github.com/cgreen-devs/cgreen/releases/latest/download/cgreen_1.2.0_amd64.deb && apt install -y ./cgreen_1.2.0_amd64.deb
      - run:
          name: Install JRE
          command: apt install -y default-jre
      - run:
          name: Unittests
          command: make UNITOUTPUT="--xml TEST"
      - run:
          name: Build
          command: make
      - run:
          name: Test
          command: make JREGROUTPUT=-xml test
      - run:
          name: Copy test results
          command: mkdir ./test_results && find . -iname 'TEST*.xml' -exec cp --parents {} ./test_results \;
      - store_test_results:
          path: ~/test_results
