version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run:
          name: Installing GCC
          command: apt-get update && apt-get install -y gcc
      - run:
          name: Installing buildessentials
          command: apt-get install -y build-essential
      - run:
          name: Unittests
          command: make UNITOUTPUT="--xml TEST"
      - run:
          name: Build
          command: make
      - run:
          name: Test
          command: make JREGROUTPUT=-xml test
      - run:
          name: Copy test results
          command: mkdir ./test_results && find . -iname 'TEST*.xml' -exec cp --parents {} ./test_results \;
      - store_test_results:
          path: ~/test_results
