#######################################################################
include ../mk/include_guard.mk
#
# This Makefile is included from the Makefile and
# only sets some cygwin particular switches
# All rules are in Makefile.common and included by Makefile

# We can potentially build for Windows
include Makefile.win32

# Flags to send to compiler and linker
CFLAGS += -funsigned-char
LDLIBS += -liconv
