#######################################################################
include ../mk/include_guard.mk
#
# This Makefile is for building the Alan System on MSYS2.
# It is included from Makefile if run on a MSYS2 MinGW shell.
#
# On Msys2 $MSYSTEM will indicate the target environment (MSYS,
# MINGW32 or MINGW64)
#
#######################################################################

# We can potentially build for Windows so include that
include Makefile.win32

# Flags to send to compiler and linker
CFLAGS +=
LDLIBS += -liconv

###########################################################
# Set relevant compilers and tools
#CC = gcc
WINDRES = windres
