#######################################################################
include ../mk/include_guard.mk
#
# Makefile settings for compiling Alan compiler on MacOS
#

CFLAGS +=
LDLIBS += -L$(ICONV_ROOT)/lib -liconv

# Sharable libraries extension
SOEXTENSION = dylib
