#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
# Makefile for compiling Alan compiler on MacOSX
#

COMPILER = gcc
LINKER = gcc

OS_FLAGS = -arch ppc -arch i386
EXTRA_COMPILER_FLAGS = -Wall -funsigned-char
EXTRA_LINKER_FLAGS = 

include rules.mk

