# Makefile for alan compiler on MacOSX
#
OSDEFS = -arch ppc -arch i386
CC = gcc
CFLAGS = -g -Wall -funsigned-char $(INCLUDE) $(OSDEFS)

LINK = gcc
LINKFLAGS = -g $(OSDEFS)


# Include common list of sources
include sources.mk

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
# Main target
#
all: unit alan test


#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
# Main target
#
alan: $(ALANOBJS)
	$(LINK) -o alan $(ALANOBJS) $(LINKFLAGS)
	-@if ! test -d ../bin; then mkdir ../bin 2> /dev/null ; fi
	cp alan ../bin


#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
# Unit testing
#

unit: unittests
	@./unittests

unittests : $(UNITOBJS)
	$(LINK) -o unittests $(CFLAGS) $(UNITOBJS) $(LINKFLAGS)

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
# Run all unit tests!
#
test: unit
	-cd testing; ../../bin/regr

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
# Clean
#
clean:
	-rm alan *.o


#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
include dependencies.mk

