#######################################################################
include ../mk/include_guard.mk
#
# Makefile settings for compiling Alan compiler on Linux
#

# We can potentially build for Windows
include Makefile.win32

release: EXTRA_COMPILER_FLAGS = -O4
