#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
# Makefile for compiling Alan compiler on MacOSX
#

COMPILER = gcc
LINKER = gcc

OS_FLAGS = -arch i386 # -arch ppc
EXTRA_COMPILER_FLAGS = -Wall -funsigned-char
EXTRA_LINKER_FLAGS = 
