#######################################################################
include ../mk/include_guard.mk
#
# Makefile settings for compiling Alan compiler on MacOSX
#

CFLAGS += -funsigned-char -Wno-invalid-source-encoding

# Sharable libraries extension
SOEXTENSION = dylib
