# Makefile for alan compiler on Unix
#

CC = gcc
CFLAGS = -g -Wall -funsigned-char $(INCLUDE) $(OSDEFS)

LINK = gcc
LINKFLAGS = -g


# Include common list of sources
include sources.mk

help:
	@echo "This the generic Makefile for the Alan compiler"
	@echo "The following targets are available:"
	@echo
	@echo "    make all  - Build and test the alan compiler"
	@echo "    make alan - Build the alan compiler"
	@echo "    make unit - Build and run the unit tests"
	@echo "    make clean

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
# Main target
#
all: unit alan test


#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
# Main target
#
alan: $(ALANOBJS)
	$(LINK) -o alan $(ALANOBJS) $(LINKFLAGS)
	-@if ! test -d ../bin; then mkdir ../bin 2> /dev/null ; fi
	cp alan ../bin


#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
# Unit testing
#

unit: unittests
	@./unittests

unittests : $(UNITOBJS)
	$(LINK) -o unittests $(CFLAGS) $(UNITOBJS) $(LINKFLAGS)

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
# Run all unit tests!
#
test: unit
	-cd testing; ../../bin/regr

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
# Clean
#
clean:
	-rm *.o


#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
include dependencies.mk

