#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
# Makefile setings for compiling Alan compiler on Linux
#

COMPILER = gcc
EXTRA_COMPILER_FLAGS = -g -Wall -funsigned-char

OSFLAGS = -m32
LINKER = gcc
EXTRA_LINKER_FLAGS = 

release: EXTRA_COMPILER_FLAGS = -O4

# Cgreen unit testing settings
CGREEN = yes
CGREENROOT = /usr/local
CGREENINCLUDE = -I$(CGREENROOT)/include
CGREENLIB = $(CGREENROOT)/lib/libcgreen.so -lm
