grammar se.alanif.alan.Alan with org.eclipse.xtext.common.Terminals

generate alan "http://www.alanif.se/Alan"

// ==========================================================================
// DRAFT -- mechanically transliterated from ParserMaker .pmk
// This grammar does NOT compile as-is. See the accompanying report.
//   * left-recursive rules are marked  TODO(left-recursion)
//   * conflict sites are marked        TODO(predicate)
//   * no cross-references ([Rule|ID]) have been inferred
// ==========================================================================

Adventure:
      OptionalOptions Declarations Start
;

// RETURNS: <nothing>
// has empty alternative -> optional at use site
OptionalOptions:
      (('options' | 'option') Options)?
;

// RETURNS: <nothing>
// TODO(left-recursion)
Options:
      Option
    | Options Option
;

// RETURNS: <nothing>
// TODO(left-factor): ID
Option:
      Id '.'
    | 'no' Id '.'
    | Id Id '.'
    | Id INT '.'
;

// TODO(left-recursion)
// has empty alternative -> optional at use site
Declarations:
      (Declarations Declaration)?
;

Declaration:
      Synonyms
    | Messages
    | Syntax
    | Verb
    | Class
    | Addition
    | Instance
    | Event
    | Rule
    | Prompt
    | 'import'
;

Prompt:
      'prompt' Statements
;

// RETURNS: atrs
// TODO(left-recursion)
Attributes:
      AttributeDefinition '.'
    | Attributes AttributeDefinition '.'
;

// RETURNS: atr
// TODO(left-factor): ID
AttributeDefinition:
      Id
    | 'not' Id
    | Id OptionalMinus INT
    | Id STRING
    | Id Id
    | Id '{' OptionalMembers '}'
;

// has empty alternative -> optional at use site
OptionalMembers:
      (SetMembers)?
;

// RETURNS: set
// TODO(left-recursion)
SetMembers:
      SetMember
    | SetMembers ',' SetMember
;

SetMember:
      What
    | OptionalMinus INT
    | STRING
;

// RETURNS: syns
Synonyms:
      'synonyms' SynonymList
;

// RETURNS: syns
// TODO(left-recursion)
SynonymList:
      SynonymDeclaration
    | SynonymList SynonymDeclaration
;

// RETURNS: syn
SynonymDeclaration:
      IdList '=' Id '.'
;

// RETURNS: msgs
Messages:
      'message' MessageList
;

// RETURNS: msgs
// TODO(left-recursion)
MessageList:
      Message
    | MessageList Message
;

// RETURNS: msg
// TODO(predicate) %+('visits') @pmk:430
Message:
      Id ':' Statements
;

Syntax:
      'syntax' SyntaxList
;

// TODO(left-recursion)
SyntaxList:
      SyntaxItem
    | SyntaxList SyntaxItem
;

SyntaxItem:
      Id '=' SyntaxElements OptionalSyntaxRestrictions
;

// TODO(left-recursion)
SyntaxElements:
      SyntaxElement
    | SyntaxElements SyntaxElement
;

SyntaxElement:
      Id
    | '(' Id ')' OptionalIndicators
;

// TODO(left-recursion)
// has empty alternative -> optional at use site
OptionalIndicators:
      (OptionalIndicators Indicator)?
;

Indicator:
      '*'
    | '!'
;

// TODO(left-recursion)
SyntaxRestrictionClauses:
      SyntaxRestriction
    | SyntaxRestrictionClauses 'and' SyntaxRestriction
;

// TODO(predicate) %+('visits') @pmk:545
SyntaxRestriction:
      Id 'isa' RestrictionClass 'else' Statements
;

// RETURNS: id, restrictionKind
RestrictionClass:
      Id
    | 'container'
;

OptionalSyntaxRestrictions:
      '.'
    | 'where' SyntaxRestrictionClauses
;

// RETURNS: vrb
Verb:
      VerbHeader VerbBody VerbTail
;

// RETURNS: srcp, str, idList
VerbHeader:
      OptionalMeta 'verb' IdList
;

// RETURNS: meta
// has empty alternative -> optional at use site
OptionalMeta:
      ('meta')?
;

VerbBody:
      SimpleVerbBody
    | VerbAlternatives
;

// TODO(left-recursion)
VerbAlternatives:
      VerbAlternative
    | VerbAlternatives VerbAlternative
;

VerbAlternative:
      'when' Id SimpleVerbBody
;

// RETURNS: srcp, chks, stms, qual
SimpleVerbBody:
      OptionalChecks OptionalDoes
;

// RETURNS: id
VerbTail:
      'end' 'verb' OptionalId '.'
;

// RETURNS: srcp, chks
// TODO(left-factor): 'check'
// has empty alternative -> optional at use site
OptionalChecks:
      ('check' Statements | 'check' CheckList)?
;

// RETURNS: chks
// TODO(left-recursion)
CheckList:
      Check
    | CheckList 'and' Check
;

// RETURNS: chk
Check:
      Expression 'else' Statements
;

// RETURNS: qual, srcp, stms
// has empty alternative -> optional at use site
OptionalDoes:
      (Does)?
;

Does:
      'does' OptionalQual Statements
;

// RETURNS: cla
Class:
      'every' Id OptionalHeritage Properties ClassTail
;

// RETURNS: id
ClassTail:
      'end' 'every' OptionalId ('.')?
;

// RETURNS: cla
Addition:
      'add' 'to' ('every')? Id OptionalHeritage Properties AddTail
;

// RETURNS: id
AddTail:
      'end' 'add' ('to')? OptionalId ('.')?
;

// RETURNS: ins
Instance:
      'the' Id OptionalHeritage Properties InstanceTail
;

// RETURNS: id
InstanceTail:
      'end' 'the' OptionalId ('.')?
;

// RETURNS: id
// has empty alternative -> optional at use site
OptionalHeritage:
      (Heritage)?
;

// RETURNS: id
Heritage:
      'isa' Id ('.')?
;

// RETURNS: all!
// TODO(left-recursion)
// has empty alternative -> optional at use site
Properties:
      (Properties Property)?
;

// TODO(predicate) %+('opaque') @pmk:1016
Property:
      Name
    | Pronoun
    | Where ('.')?
    | Is Attributes
    | Initialize
    | ContainerProperties
    | Description
    | Entered
    | Mentioned
    | ('indefinite')? ArticleOrForm
    | 'definite' ArticleOrForm
    | 'negative' ArticleOrForm
    | Exit
    | Verb
    | Script
;

// RETURNS: ext
Exit:
      'exit' IdList 'to' Id OptionalExitBody '.'
;

// RETURNS: chks, stms, id
// has empty alternative -> optional at use site
OptionalExitBody:
      (OptionalChecks OptionalDoes 'end' 'exit' OptionalId)?
;

// RETURNS: srcp
Is:
      'is'
    | 'are'
    | 'has'
    | 'can'
;

// RETURNS: description
// has empty alternative -> optional at use site
OptionalDescription:
      (Description)?
;

// RETURNS: description
// TODO(left-factor): 'description'
Description:
      'description' OptionalChecks OptionalDoes
    | 'description' Statements
;

ArticleOrForm:
      Article
    | Form
;

// RETURNS: article
// TODO(left-factor): 'article'
Article:
      'article'
    | 'article' Statements
;

// RETURNS: stms, srcp
// TODO(left-factor): 'form'
Form:
      'form'
    | 'form' Statements
;

// RETURNS: stms, srcp
Entered:
      'entered' Statements
;

// RETURNS:  
Initialize:
      'initialize' Statements
;

// RETURNS: stms, srcp
Mentioned:
      'mentioned' Statements
;

// RETURNS: nam
Name:
      'name' Ids OptionalFullStop
;

// RETURNS: idList
Pronoun:
      'pronoun' IdList OptionalFullStop
;

// TODO(predicate) %+('opaque') @pmk:1301
// has empty alternative -> optional at use site
OptionalFullStop:
      ('.')?
;

// RETURNS: cnt, srcp
ContainerProperties:
      ('with')? OptionallyOpaque 'container' ContainerBody
;

// has empty alternative -> optional at use site
OptionallyOpaque:
      ('opaque')?
;

// RETURNS: lims, stms, stms2
ContainerBody:
      OptionalTaking OptionalLimits OptionalHeader OptionalEmpty OptionalExtract
    | '.'
;

// RETURNS: id
// has empty alternative -> optional at use site
OptionalTaking:
      ('taking' Id '.')?
;

// RETURNS: lims
// TODO(predicate) %+('opaque') @pmk:1371
// has empty alternative -> optional at use site
OptionalLimits:
      ('limits' Limits)?
;

// RETURNS: lims
// TODO(left-recursion)
Limits:
      Limit
    | Limits Limit
;

// RETURNS: lim
// TODO(predicate) %+('visits') @pmk:1390
Limit:
      LimitAttribute ElseOrThen Statements
;

// RETURNS: srcp
ElseOrThen:
      'else'
    | 'then'
;

// RETURNS: atr
LimitAttribute:
      AttributeDefinition
    | 'count' INT
;

// RETURNS: stms
// has empty alternative -> optional at use site
OptionalHeader:
      ('header' Statements)?
;

// RETURNS: stms
// has empty alternative -> optional at use site
OptionalEmpty:
      ('else' Statements)?
;

// RETURNS: chks, stms
// TODO(left-factor): 'extract'
// has empty alternative -> optional at use site
OptionalExtract:
      ('extract' OptionalChecks OptionalDoes | 'extract' Statements)?
;

// RETURNS: evt
Event:
      EventHeader Statements EventTail
;

// RETURNS: srcp, id
EventHeader:
      'event' Id
;

// RETURNS: id
EventTail:
      'end' 'event' OptionalId '.'
;

// RETURNS: scr
Script:
      'script' Id ('.')? OptionalDescription StepList
;

// RETURNS: stps
// TODO(left-recursion)
StepList:
      Step
    | StepList Step
;

// RETURNS: stp
// TODO(left-factor): 'step'
Step:
      'step' Statements
    | 'step' 'after' Expression ('.')? Statements
    | 'step' 'wait' 'until' Expression ('.')? Statements
;

// RETURNS: rul
Rule:
      'when' Expression Then Statements OptionalEndWhen
;

Then:
      '=>'
    | 'then'
;

// has empty alternative -> optional at use site
OptionalEndWhen:
      ('end' 'when' ('.')?)?
;

Start:
      'start' Where '.' OptionalStatements
;

// RETURNS: stms
// has empty alternative -> optional at use site
OptionalStatements:
      (Statements)?
;

// RETURNS: stms
// TODO(left-recursion)
Statements:
      Statement
    | Statements Statement
;

// RETURNS: stm
Statement:
      OutputStatement
    | ManipulationStatement
    | AssignmentStatement
    | ConditionalStatement
    | RepetitionStatement
    | ActorStatement
    | EventStatement
    | SpecialStatement
;

// RETURNS: stm
// TODO(predicate) %-('is','are','has','can','at','here','in','nearby','near','transitively','directly','indirectly') @pmk:1642
OutputStatement:
      STRING
    | 'describe' What '.'
    | 'say' SayForm Expression '.'
    | 'list' Primary '.'
    | 'show' Id '.'
    | 'play' Id '.'
    | 'style' Id '.'
;

// TODO(predicate) %-('it') @pmk:1683
// has empty alternative -> optional at use site
SayForm:
      ('the' | 'an' | 'it' | 'no')?
;

// RETURNS: stm
ManipulationStatement:
      'empty' Primary OptionalWhere '.'
    | 'locate' Primary Where '.'
    | 'include' Primary 'in' What '.'
    | 'exclude' Primary 'from' What '.'
;

// RETURNS: stm
EventStatement:
      'schedule' What OptionalWhere 'after' Expression '.'
    | 'cancel' What '.'
;

// RETURNS: stm
AssignmentStatement:
      'make' Primary Something '.'
    | 'set' AttributeReference 'to' Expression '.'
    | 'increase' AttributeReference OptionalByClause '.'
    | 'decrease' AttributeReference OptionalByClause '.'
    | 'strip' OptionalFirstOrLast OptionalExpression OptionalWordOrCharacter 'from' Expression OptionalInto '.'
;

// has empty alternative -> optional at use site
OptionalByClause:
      ('by' Expression)?
;

// RETURNS: first
// TODO(predicate) %-('first') @pmk:1800
// has empty alternative -> optional at use site
OptionalFirstOrLast:
      ('first' | 'last')?
;

// has empty alternative -> optional at use site
OptionalWordOrCharacter:
      ('word' | 'words' | 'character' | 'characters')?
;

// has empty alternative -> optional at use site
OptionalInto:
      ('into' Expression)?
;

ConditionalStatement:
      IfStatement
    | DependingStatement
;

// RETURNS: stm
IfStatement:
      'if' Expression 'then' Statements OptionalElsifList OptionalElsePart 'end' 'if' '.'
;

// has empty alternative -> optional at use site
OptionalElsifList:
      (ElsifList)?
;

// RETURNS: stms
// TODO(left-recursion)
ElsifList:
      'elsif' Expression 'then' Statements
    | ElsifList 'elsif' Expression 'then' Statements
;

// RETURNS: stms
// has empty alternative -> optional at use site
OptionalElsePart:
      ('else' Statements)?
;

DependingStatement:
      'depending' 'on' Primary DependCases 'end' ('depend' | 'depending') '.'
;

// RETURNS: cases
// TODO(left-recursion)
DependCases:
      DependCase
    | DependCases DependCase
;

// RETURNS: stm
DependCase:
      RightHandSide 'then' Statements
    | 'else' Statements
;

// RETURNS: stm
RepetitionStatement:
      ForEach Id OptionalLoopFilters 'do' Statements 'end' ForEach ('.')?
;

// RETURNS: ID
// has empty alternative -> optional at use site
OptionalLoopFilters:
      (Filters | 'between' Arithmetic 'and' Arithmetic)?
;

// TODO(predicate) %-('each') @pmk:1990
// TODO(left-factor): 'for'
ForEach:
      'for'
    | 'each'
    | 'for' 'each'
;

// RETURNS: stm
ActorStatement:
      'use' 'script' Id OptionalForActor '.'
    | 'stop' What '.'
;

// RETURNS: exp
// has empty alternative -> optional at use site
OptionalForActor:
      ('for' What)?
;

// RETURNS: stm
SpecialStatement:
      'quit' '.'
    | 'look' '.'
    | 'save' '.'
    | 'restore' '.'
    | 'restart' '.'
    | 'score' OptionalInteger '.'
    | 'visits' INT '.'
    | 'transcript' OnOrOff '.'
    | 'system' STRING '.'
;

OnOrOff:
      'on'
    | 'off'
;

// RETURNS: exp
// has empty alternative -> optional at use site
OptionalExpression:
      (Expression)?
;

// RETURNS: exp
// TODO(left-recursion)
Expression:
      Term
    | Expression 'or' Term
;

// RETURNS: exp
// TODO(left-recursion)
Term:
      Factor
    | Term 'and' Factor
;

// RETURNS: exp
// TODO(left-recursion)
// TODO(left-factor): factor
Factor:
      Arithmetic
    | Factor OptionalNot Relop Arithmetic
    | Factor OptionalNot Where
    | Factor OptionalNot 'between' Arithmetic 'and' Arithmetic
    | Factor OptionalNot 'contains' Arithmetic
;

// TODO(left-recursion)
// TODO(left-factor): primary
Arithmetic:
      Primary
    | Primary 'isa' Id
    | Primary Is Something
    | Arithmetic Binop Primary
    | Aggregate Filters
;

// RETURNS: exps
// TODO(left-recursion)
Filters:
      Filter
    | Filters ',' Filter
;

// RETURNS: exp
// TODO(left-factor): optional_not
Filter:
      OptionalNot Where
    | OptionalNot 'isa' Id
    | Is Something
;

// TODO(left-factor): optional_not
RightHandSide:
      OptionalNot Relop Primary
    | OptionalNot 'between' Arithmetic 'and' Arithmetic
    | OptionalNot 'contains' Factor
    | Filter
;

// RETURNS: exp
// TODO(predicate) %+('is','are','has','can','at','here','in','nearby','near','transitively','directly','indirectly') @pmk:2305
// TODO(left-factor): 'random'
Primary:
      '(' Expression ')'
    | OptionalMinus INT
    | STRING
    | What
    | 'random' Primary 'to' Primary
    | 'random' OptionalTransitivity 'in' Primary
    | 'score'
    | '{' OptionalMembers '}'
;

// RETURNS: srcp, agr, id
Aggregate:
      Aggregator 'of' Id
    | 'count'
;

Aggregator:
      'max'
    | 'min'
    | 'sum'
;

// RETURNS: not, id
Something:
      OptionalNot Id
;

// RETURNS: exp
What:
      SimpleWhat
    | AttributeReference
;

// RETURNS: srcp, wht
// TODO(predicate) %-('of') @pmk:2398
// TODO(left-factor): 'current'
SimpleWhat:
      Id
    | 'current' 'actor'
    | 'current' 'location'
    | 'this'
;

// RETURNS: exp
// TODO(predicate) %-(':') @pmk:2425
AttributeReference:
      Id 'of' What
    | What ':' Id
;

// RETURNS: whr
// has empty alternative -> optional at use site
OptionalWhere:
      (Where)?
;

// RETURNS: srcp, whr
// TODO(left-factor): optional_transitivity
Where:
      OptionalTransitivity 'here'
    | OptionalTransitivity 'nearby'
    | OptionalTransitivity 'at' Primary
    | OptionalTransitivity 'in' Primary
    | OptionalTransitivity 'near' What
;

// RETURNS: op, srcp
Binop:
      '+'
    | '-'
    | '*'
    | '/'
;

// RETURNS: op, srcp
Relop:
      '<>'
    | '='
    | '=='
    | '>='
    | '<='
    | '>'
    | '<'
;

// RETURNS: qual, srcp
// has empty alternative -> optional at use site
OptionalQual:
      ('before' | 'after' | 'only')?
;

// TODO(predicate) %+(Identifier,'on','of','into','first','actor','opaque','taking','location') @pmk:2580
// has empty alternative -> optional at use site
OptionalNot:
      ('not')?
;

// has empty alternative -> optional at use site
OptionalTransitivity:
      ('transitively' | 'directly' | 'indirectly')?
;

// has empty alternative -> optional at use site
OptionalId:
      (Id)?
;

// RETURNS: idList
// TODO(left-recursion)
Ids:
      Id
    | Ids Id
;

// RETURNS: str, idList
// TODO(left-recursion)
IdList:
      Id
    | IdList ',' Id
;

// RETURNS: str
// has empty alternative -> optional at use site
OptionalInteger:
      (INT)?
;

// RETURNS: minus
// has empty alternative -> optional at use site
OptionalMinus:
      ('-')?
;

Id:
      ID
    | 'location'
    | 'actor'
    | 'opaque'
    | 'visits'
    | 'contains'
    | 'on'
    | 'it'
    | 'of'
    | 'first'
    | 'into'
    | 'taking'
    | 'off'
;
