####################################################################
include ../mk/include_guard.mk
#
# This file is included from Makefile. It includes special settings
# to build Alan Interpreter(s) on Linux. Common rules are in
# Makefile.common

# We are compiling for the same version as on Master version system

# It should be possible to build win32 binaries so include those targets
include Makefile.win32

LIBS = $(GLKLIB) $(LINKLIBS)


#############################################################
# GARARUN: a Gargoyle drop-in alan interpreter
#
# To build GARGOYLE_ROOT should be set to where the Gargoyle sources
# are and have its directory terps/alan3 linked to
# alan/interpreter. All required libraries, including libgarglk.so
# need to be built to binary form before making it from here.  It is
# built with jam, so "alan3", the resulting Alan interpreter drop-in,
# will be available as
# $(GARGOYLE_ROOT)/build/<arch>.release/alan3/alan3
ifdef GARARUN_ENABLED
EXTRA_TARGETS += gargoyle
else
$(info NOT ENABLED: gararun - Gargoyle Arun for Linux)
endif

gararun: gararun-zip gararun-sh

gararun-zip: alan3
	tar zcvf gargoyle-alan3-$(VERSION)$(BUILDVERSION).linux.tgz alan3 gargoyle-updater-alan3.readme

gararun-sh: alan3
	mkdir -p gargoyle-alan3-updater
	cp alan3 gargoyle-alan3-updater
	cp gargoyle-updater-chooser-linux.sh gargoyle-alan3-updater
	makeself --base64 gargoyle-alan3-updater gargoyle-updater-alan3-$(VERSION)$(BUILDVERSION).linux.sh "Alan v3 Gargoyle updater" ./gargoyle-updater-chooser-linux.sh
	rm -rf gargoyle-alan3-updater

alan3:
	cd $(GARGOYLE_ROOT); jam STATIC=1 alan3
	cp $(GARGOYLE_ROOT)/build/linux.release/alan3/alan3 .
