#######################################################################
include ../mk/include_guard.mk
#
# This makefile is included by all Makefile.<platform> where Windows
# binaries can be made. You can configure where any dependent
# libraries are stored, compiler switches in Makefile.local (which
# should be copied from Makefile.local.template
#
# You can also disable a particular build by commenting out the settings
# of EXTRA_TARGETS.
#

INNODIR = /cygdrive/c/Program\ Files\ \(x86\)/Inno\ Setup\ 5

#######################################################################
# WinArun - Windows GLK interpreter
#
# Define WINGLK_ROOT to enable building
ifdef WINARUN_ENABLED
EXTRA_TARGETS += winarun
else
$(info NOT ENABLED: winarun - WindowsGLK-based Arun)
endif

WINGLK_DEFS = -DHAVE_WINGLK
WINGLK_INCLUDE = -I$(WINGLK_ROOT)/Include
WINGLK_LIB = $(WINGLK_ROOT)/Glk.lib # or -L$(WINGLK_ROOT) -l:Glk.lib

# WindowsGlk is a 32-bit library -- see the note on MINGW32_PREFIX in
# mk/common.mk -- so winarun is the one Windows target we build with the
# 32-bit toolchain. Defaulting it here rather than in Makefile.local means
# a clean checkout can build it at all; Makefile.local stays the place to
# say whether it *should* be built, and to override any of this.
#
# Note the indirection. We are included after Makefile.local, so a
# target-specific 'winarun: CC =' here would silently beat anything set
# there -- and beat Makefile.Msys's plain 'CC = gcc' too, where the native
# MinGW compiler has no prefix at all. Going through an ordinary '?='
# variable keeps the override working from both.
WINARUN_CC ?= $(MINGW32_PREFIX)-gcc
WINARUN_WINDRES ?= $(MINGW32_PREFIX)-windres

# Target-specific variables reach the prerequisites too, so the objects
# and winarun.res are built with the same compiler and windres.
winarun: CC = $(WINARUN_CC)
winarun: WINDRES = $(WINARUN_WINDRES)
winarun: CFLAGS += $(WINGLK_INCLUDE) $(WINGLK_DEFS) -mwindows -I$(WINICONV32_ROOT)
winarun: LDFLAGS += -mwindows
winarun: LDLIBS += -L$(WINICONV32_ROOT) -l:libwiniconv.a
winarun: EXEEXT = .exe

WINARUNOBJDIR = .winarun
WINARUNOBJECTS = $(addprefix $(WINARUNOBJDIR)/,${WINARUNSRCS:.c=.o}) $(WINARUNOBJDIR)/alan.version.o
-include $(WINARUNOBJECTS:.o=.d)
$(WINARUNOBJECTS): $(WINARUNOBJDIR)/%.o: %.c
	$(COMPILE) -MMD -o $@ -c $<

$(WINARUNOBJDIR):
	mkdir $(WINARUNOBJDIR)

winarun: $(WINARUNOBJDIR) $(WINARUNOBJECTS) winarun.res
	$(LINK) -o $@$(EXEEXT) $(WINARUNOBJECTS) winarun.res $(WINGLK_LIB) $(LDLIBS)
	cp $@$(EXEEXT) ../bin/
	cp $(WINGLK_ROOT)/*.dll ../bin/

winarun.res: winarun.rc winarun.ico resources.h alan.version.c
	sed "s/WINARUNVERSION/$(VERSION)$(BUILDVERSION)/" winarun.rc > winarun.rc2
	$(WINDRES) winarun.rc2 -O coff -o $@


#######################################################################
# Gargoyle for Windows GLK variant
#
# Requires:
#	GARGOYLE_ROOT - Make variable
#       - set to the root of directory for Gargoyle sources (for includes)
#   libgarglk.dll - file
#   libgarglkmain.a - file
#   icons.o - compiled version of Gargoyle icons
#       - these are in the subdirectory "garglk", which we can use as
#         long as the interface or icons of Gargoyle does not change.
#         Then it need to be rebuilt from the Gargoyle sources

#
# Test by copying alan3.exe into the Gargoyle directory (over existing
# alan3.exe) and run an Alan v3 game using Gargoyle.
#
ifdef GARARUN_ENABLED
EXTRA_TARGETS += gargoyle
else
$(info NOT ENABLED: gararun - Gargoyle Arun for Windows)
endif

GARARUNOBJDIR = .gararun
GARARUNOBJECTS = $(addprefix $(GARARUNOBJDIR)/,${GARARUNSRCS:.c=.o}) $(GARARUNOBJDIR)/alan.version.o
-include $(GARARUNOBJECTS:.o=.d)

$(GARARUNOBJECTS): $(GARARUNOBJDIR)/%.o: %.c
	$(COMPILE) -MMD -o $@ -c $<

$(GARARUNOBJDIR):
	mkdir $(GARARUNOBJDIR)

gararun: CFLAGS += -DHAVE_GARGLK -I$(GARGOYLE_ROOT)/garglk
gararun: build-gararun gararun-package gargoyle-updater
gararun: GARARUNLIBS = garglk/libgarglkmain.a garglk/libgarglk.dll garglk/icons.o
gararun: LDFLAGS := -lcomdlg32 -lgdi32 -lwinmm -mwindows

.PHONY: build-gararun
build-gararun: alan3.exe

alan3.exe: $(GARARUNOBJDIR) $(GARARUNOBJECTS)
	$(LINK) -o $@ $(GARARUNOBJECTS) $(GARARUNLIBS)

.PHONY: gararun-package
gararun-package: build-gararun gargoyle-updater-alan3.readme
	zip -j gargoyle-updater-alan$(VERSION)$(BUILDVERSION).$(PLATFORM).zip alan3.exe gargoyle-updater-alan3.readme

.PHONY: gargoyle-updater
gargoyle-updater: build-gararun gargoyle-updater-alan3.nsi
	-rm gargoyle-updater-alan3*setup.exe
	sed -e s/VERSION/$(VERSION)$(BUILDVERSION)/ gargoyle-updater-alan3.nsi > gargoyle-updater-alan3_tmp.nsi
	makensis gargoyle-updater-alan3_tmp.nsi
	rm gargoyle-updater-alan3_tmp.nsi
