#######################################################################
include ../mk/include_guard.mk
#
# This Makefile is for building the Alan Interpreter on MSYS2. It is
# included from Makefile if run on a MSYS2 MinGW shell.
#
# NOTE: This file is an adaptation of "Makefile.cygwin", it hasn't been
#       tested with CGreen yet.
#######################################################################

# It should be possible to build win32 binaries, so include those targets
include Makefile.win32

CFLAGS +=
LDLIBS += -liconv

###########################################################
# Set relevant default compilers and tools
#
CC = gcc
WINDRES = windres

# Native MinGW: no cross prefix, so winarun uses the same compiler as
# everything else here. Must be these variables rather than 'winarun: CC',
# which Makefile.win32 would override.
WINARUN_CC = gcc
WINARUN_WINDRES = windres
